export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIE_DETAILS = 'RECEIVE_MOVIE_DETAILS';
export const RECEIVE_RELATED_MOVIES = 'RECEIVE_RELATED_MOVIES';
export const SORT_BY = 'SORT_BY';
export const SEARCH_BY = 'SEARCH_BY';
export const SEARCH_TEXT = 'SEARCH_TEXT';
